### PR TITLE
Convert erb files to haml files

### PR DESCRIPTION
**Pull request by romasks**

### CODE REVIEW

**Comment by Mehonoshin** [comment]
@romasks rebase please your branch

**Comment by Mehonoshin** [comment]
@romasks rebase please, and I'll merge

**Comment by romasks** [comment]
@Mehonoshin done. Sorry for late answer!

**Comment by Mehonoshin** [comment]
@romasks wow, I see a lot of commits it this PR. They should not be here.
Can you just recreate branch and cherry-pick just your commit here?

**Comment by romasks** [comment]
@Mehonoshin sorry for so late answer! Is still actual to cherry-pick my changes?

**Comment by Mehonoshin** [comment]
@romasks yes it is

**Pull request merged**
